/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airline_project;

import java.awt.Color; // For custom colors
import java.awt.Font; // For setting fonts
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField; // For casting if needed, though JPasswordField is now used

/**
 * A JInternalFrame for adding new Admin users to the system.
 * It includes fields for Admin ID (auto-generated), first name, last name,
 * username, and password.
 *
 * @author ranji
 */
public class AddAdmin extends javax.swing.JInternalFrame {

    private static final Logger LOGGER = Logger.getLogger(AddAdmin.class.getName());
    private static final int TEXT_FIELD_WIDTH = 150; // Define a consistent width

    /**
     * Establishes and returns a connection to the MySQL database.
     *
     * @return A Connection object.
     * @throws SQLException If a database access error occurs.
     * @throws ClassNotFoundException If the MySQL JDBC driver class is not found.
     */
    public Connection getConnection() throws SQLException, ClassNotFoundException {
        Class.forName("com.mysql.cj.jdbc.Driver");
        // Consider externalizing connection details for production
        return DriverManager.getConnection("jdbc:mysql://127.0.0.1/airline-database", "root", "Ranjith@1654R");
    }

    /**
     * Generates and sets a new unique Admin ID in the adminIdTextField.
     * The ID is in the format "ADXXX", where XXX is a zero-padded number.
     */
    public void autoID() {
        String sql = "SELECT MAX(adminID) AS max_id FROM admin";
        try (Connection con = getConnection();
             PreparedStatement pre = con.prepareStatement(sql);
             ResultSet rs = pre.executeQuery()) {

            if (rs.next()) {
                String maxId = rs.getString("max_id");
                if (maxId == null) {
                    adminIdTextField.setText("AD001");
                } else {
                    // Extract numeric part (e.g., from "AD005" to 5)
                    long id = Long.parseLong(maxId.substring(2));
                    id++;
                    adminIdTextField.setText("AD" + String.format("%03d", id)); // Format to AD001, AD002, etc.
                }
            } else {
                // Should not happen if MAX() is used, but as a fallback
                adminIdTextField.setText("AD001");
            }
        } catch (SQLException ex) {
            LOGGER.log(Level.SEVERE, "SQL error during AutoID generation.", ex);
            JOptionPane.showMessageDialog(this, "Error generating Admin ID: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            adminIdTextField.setText("Error"); // Indicate an error state
        } catch (ClassNotFoundException ex) {
            LOGGER.log(Level.SEVERE, "MySQL JDBC Driver not found during AutoID.", ex);
            JOptionPane.showMessageDialog(this, "Database driver error: " + ex.getMessage(), "Driver Error", JOptionPane.ERROR_MESSAGE);
            adminIdTextField.setText("Error");
        } catch (NumberFormatException ex) {
            LOGGER.log(Level.SEVERE, "Error parsing existing Admin ID.", ex);
            JOptionPane.showMessageDialog(this, "Error parsing Admin ID from database.", "Data Format Error", JOptionPane.ERROR_MESSAGE);
            adminIdTextField.setText("Error");
        }
    }

    /**
     * Creates new form AddAdmin.
     * Initializes components, sets background color, and generates an Admin ID.
     *
     * @throws SQLException (This constructor was declared to throw SQLException,
     *                      but AutoID now handles its own exceptions. Consider removing if not needed
     *                      by other initialization logic not shown.)
     */
    public AddAdmin() throws SQLException { // Consider if SQLException is still needed here
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.LIGHT_GRAY); // A slightly lighter gray
        autoID();
        adminIdTextField.setEditable(false); // Admin ID is auto-generated
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageTitleLabel = new javax.swing.JLabel();
        adminFormPanel = new javax.swing.JPanel();
        adminIdLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        adminIdTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add New Admin");

        pageTitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageTitleLabel.setText("Welcome to the Admin Panel");

        adminFormPanel.setBackground(new java.awt.Color(204, 204, 204));
        adminFormPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adminIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminIdLabel.setText("Admin ID :");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name : ");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name :");

        firstNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameTextField.setPreferredSize(new java.awt.Dimension(TEXT_FIELD_WIDTH, 26));

        adminIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminIdTextField.setPreferredSize(new java.awt.Dimension(TEXT_FIELD_WIDTH, 26));

        lastNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameTextField.setPreferredSize(new java.awt.Dimension(TEXT_FIELD_WIDTH, 26));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setText("Username :");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setText("Password :");

        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTextField.setPreferredSize(new java.awt.Dimension(TEXT_FIELD_WIDTH, 26));

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(TEXT_FIELD_WIDTH, 26));

        javax.swing.GroupLayout adminFormPanelLayout = new javax.swing.GroupLayout(adminFormPanel);
        adminFormPanel.setLayout(adminFormPanelLayout);
        adminFormPanelLayout.setHorizontalGroup(
                adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminFormPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(adminFormPanelLayout.createSequentialGroup()
                                                .addComponent(lastNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminFormPanelLayout.createSequentialGroup()
                                                .addComponent(firstNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminFormPanelLayout.createSequentialGroup()
                                                .addComponent(adminIdLabel)
                                                .addGap(30, 30, 30)
                                                .addComponent(adminIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel)
                                        .addComponent(passwordLabel))
                                .addGap(18, 18, 18)
                                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20))
        );

        adminFormPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminIdTextField, firstNameTextField, lastNameTextField, passwordField, usernameTextField});

        adminFormPanelLayout.setVerticalGroup(
                adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminFormPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(adminIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameLabel)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameLabel)
                                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLabel)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        addButton.setBackground(new java.awt.Color(0, 153, 255));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(204, 204, 204));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adminFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(20, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(pageTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(adminFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action performed when the "Add" button is clicked.
     * Validates input fields and inserts a new admin record into the database.
     *
     * @param evt The action event.
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String adminIDValue = adminIdTextField.getText();
        String firstNameValue = firstNameTextField.getText();
        String lastNameValue = lastNameTextField.getText();
        String usernameValue = usernameTextField.getText();
        String passwordValue = new String(passwordField.getPassword()); // Get password from JPasswordField

        // Basic Validation
        if (adminIDValue.isEmpty() || firstNameValue.isEmpty() || lastNameValue.isEmpty() || usernameValue.isEmpty() || passwordValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ("Error".equals(adminIDValue)){
            JOptionPane.showMessageDialog(this, "Admin ID generation failed. Cannot add admin.", "ID Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        String sql = "INSERT INTO admin(adminID, firstName, lastName, username, password) VALUES (?, ?, ?, ?, ?)";

        try (Connection con = getConnection();
             PreparedStatement pre = con.prepareStatement(sql)) {

            pre.setString(1, adminIDValue);
            pre.setString(2, firstNameValue);
            pre.setString(3, lastNameValue);
            pre.setString(4, usernameValue);
            pre.setString(5, passwordValue); // Store plain text password (Hashing is recommended for production)

            pre.executeUpdate();

            JOptionPane.showMessageDialog(this, "Admin Added Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Optionally, clear fields or close window
            // firstNameTextField.setText("");
            // lastNameTextField.setText("");
            // usernameTextField.setText("");
            // passwordField.setText("");
            // autoID(); // Generate new ID for next entry
            this.dispose(); // Close the window after adding

        } catch (ClassNotFoundException ex) {
            LOGGER.log(Level.SEVERE, "MySQL JDBC Driver not found.", ex);
            JOptionPane.showMessageDialog(this, "Database driver error: " + ex.getMessage(), "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            LOGGER.log(Level.SEVERE, "SQL error while adding admin.", ex);
            if (ex.getErrorCode() == 1062) { // MySQL error code for duplicate entry
                JOptionPane.showMessageDialog(this, "Error adding admin: Admin ID or Username already exists.\n" + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error adding admin: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * Handles the action performed when the "Cancel" button is clicked.
     * Closes the AddAdmin internal frame.
     *
     * @param evt The action event.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose(); // Closes the JInternalFrame
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel adminFormPanel;
    private javax.swing.JLabel adminIdLabel;
    private javax.swing.JTextField adminIdTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}