package com.mycompany.airline_project;

import java.awt.Color; // For Desktop background (optional)
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame; // For JFrame.MAXIMIZED_BOTH
// import javax.swing.ImageIcon; // For icons (optional, ensure you have icons in your resources)
// import javax.swing.JOptionPane; // For user-friendly error messages (optional)

/**
 * Main window for the Airline Reservation System.
 * This JFrame serves as the main container for various internal frames
 * such as adding customers, flights, booking tickets, etc.
 *
 * @author ranji
 */
public class Main extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main.
     * Initializes components and sets the frame to be maximized.
     */
    public Main() {
        initComponents();
        // Set the frame to be maximized by default for a better user experience
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        customerMenu = new javax.swing.JMenu();
        addCustomerMenuItem = new javax.swing.JMenuItem();
        searchCustomerMenuItem = new javax.swing.JMenuItem();
        flightMenu = new javax.swing.JMenu();
        addFlightMenuItem = new javax.swing.JMenuItem();
        bookFlightMenuItem = new javax.swing.JMenuItem();
        ticketMenu = new javax.swing.JMenu();
        viewTicketMenuItem = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();
        addAdminMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airline Reservation System");

        // Optional: Set a background color for the JDesktopPane
        mainDesktopPane.setBackground(new java.awt.Color(220, 230, 240)); // Light blue-gray

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
                mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE) // Default width
        );
        mainDesktopPaneLayout.setVerticalGroup(
                mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 550, Short.MAX_VALUE) // Default height
        );

        customerMenu.setText("Customer");
        customerMenu.setMnemonic('C'); // Alt+C

        // Example: Add icon and accelerator to "Add Customer"
        // addCustomerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_customer_icon.png"))); // Ensure icon exists
        addCustomerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addCustomerMenuItem.setText("Add Customer");
        addCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMenuItemActionPerformed(evt);
            }
        });
        customerMenu.add(addCustomerMenuItem);

        // searchCustomerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search_customer_icon.png")));
        searchCustomerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        searchCustomerMenuItem.setText("Search Customer");
        searchCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerMenuItemActionPerformed(evt);
            }
        });
        customerMenu.add(searchCustomerMenuItem);

        mainMenuBar.add(customerMenu);

        flightMenu.setText("Flight");
        flightMenu.setMnemonic('F'); // Alt+F

        // addFlightMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_flight_icon.png")));
        addFlightMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addFlightMenuItem.setText("Add Flight");
        addFlightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightMenuItemActionPerformed(evt);
            }
        });
        flightMenu.add(addFlightMenuItem);

        // bookFlightMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_flight_icon.png")));
        bookFlightMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bookFlightMenuItem.setText("Book Flight");
        bookFlightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightMenuItemActionPerformed(evt);
            }
        });
        flightMenu.add(bookFlightMenuItem);

        mainMenuBar.add(flightMenu);

        ticketMenu.setText("Ticket");
        ticketMenu.setMnemonic('T'); // Alt+T

        // viewTicketMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_ticket_icon.png")));
        viewTicketMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        viewTicketMenuItem.setText("View Ticket");
        viewTicketMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketMenuItemActionPerformed(evt);
            }
        });
        ticketMenu.add(viewTicketMenuItem);

        mainMenuBar.add(ticketMenu);

        adminMenu.setText("Admin");
        adminMenu.setMnemonic('A'); // Alt+A

        // addAdminMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_admin_icon.png")));
        addAdminMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addAdminMenuItem.setText("Add Admin");
        addAdminMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminMenuItemActionPerformed(evt);
            }
        });
        adminMenu.add(addAdminMenuItem);

        mainMenuBar.add(adminMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainDesktopPane)
        );

        pack();
        setLocationRelativeTo(null); // Center the window on screen (effective if not maximized initially)
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the "Add Customer" menu item.
     * Opens the AddCustomer internal frame.
     *
     * @param evt The action event.
     */
    private void addCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMenuItemActionPerformed
        AddCustomer addCustomerFrame = new AddCustomer();
        this.mainDesktopPane.add(addCustomerFrame);
        addCustomerFrame.setVisible(true);
    }//GEN-LAST:event_addCustomerMenuItemActionPerformed

    /**
     * Handles the action event for the "Search Customer" menu item.
     * Opens the SearchCustomer internal frame.
     *
     * @param evt The action event.
     */
    private void searchCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerMenuItemActionPerformed
        SearchCustomer searchCustomerFrame = new SearchCustomer();
        this.mainDesktopPane.add(searchCustomerFrame);
        searchCustomerFrame.setVisible(true);
    }//GEN-LAST:event_searchCustomerMenuItemActionPerformed

    /**
     * Handles the action event for the "Add Flight" menu item.
     * Opens the AddFlight internal frame.
     *
     * @param evt The action event.
     */
    private void addFlightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightMenuItemActionPerformed
        AddFlight addFlightFrame = new AddFlight();
        this.mainDesktopPane.add(addFlightFrame);
        addFlightFrame.setVisible(true);
    }//GEN-LAST:event_addFlightMenuItemActionPerformed

    /**
     * Handles the action event for the "Add Admin" menu item.
     * Opens the AddAdmin internal frame.
     *
     * @param evt The action event.
     */
    private void addAdminMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminMenuItemActionPerformed
        try {
            AddAdmin addAdminFrame = new AddAdmin();
            this.mainDesktopPane.add(addAdminFrame);
            addAdminFrame.setVisible(true);
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error opening Add Admin window", e);
            // Optionally, show a user-friendly error message here using JOptionPane
            // JOptionPane.showMessageDialog(this, "Could not open Add Admin window: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addAdminMenuItemActionPerformed

    /**
     * Handles the action event for the "Book Flight" menu item.
     * Opens the BookTicket internal frame.
     *
     * @param evt The action event.
     */
    private void bookFlightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightMenuItemActionPerformed
        try {
            BookTicket bookTicketFrame = new BookTicket();
            this.mainDesktopPane.add(bookTicketFrame);
            bookTicketFrame.setVisible(true);
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error opening Book Ticket window", e);
            // JOptionPane.showMessageDialog(this, "Could not open Book Ticket window: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bookFlightMenuItemActionPerformed

    /**
     * Handles the action event for the "View Ticket" menu item.
     * Opens the GetTicket internal frame.
     *
     * @param evt The action event.
     */
    private void viewTicketMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketMenuItemActionPerformed
        GetTicket getTicketFrame = new GetTicket();
        this.mainDesktopPane.add(getTicketFrame);
        getTicketFrame.setVisible(true);
    }//GEN-LAST:event_viewTicketMenuItemActionPerformed

    /**
     * Main method to launch the application.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            LOGGER.log(Level.SEVERE, "Nimbus L&F not found or could not be set.", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAdminMenuItem;
    private javax.swing.JMenuItem addCustomerMenuItem;
    private javax.swing.JMenuItem addFlightMenuItem;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenuItem bookFlightMenuItem;
    private javax.swing.JMenu customerMenu;
    private javax.swing.JMenu flightMenu;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem searchCustomerMenuItem;
    private javax.swing.JMenu ticketMenu;
    private javax.swing.JMenuItem viewTicketMenuItem;
    // End of variables declaration//GEN-END:variables
}